-- ca_clubs step 3 of 5 - Central Assign's club list, verbatim
-- Split out of ca-clubs.sql so each piece can be run and checked on its own.
-- Run with SQL Editor > Execute script (Alt+X), not Ctrl+Enter.
-- Step 1 (create table public.ca_clubs) was run 2026-09-03 11:49.
-- ---------------------------------------------------------------------------

-- Run step 2 FIRST. Without the unique index, re-running this file inserts
-- every club a second time - ON CONFLICT DO NOTHING has nothing to catch on.

-- 140 names read off CA's Home Club dropdown on 2026-09-03. PARTIAL: no I
-- section, nothing past Woodbury Bethlehem. CA's own typos are deliberate -
-- "Tournment", "Lyme-Old lyme Soccer Club", "Cantebury Soccer Club".
-- Expect: 140 rows, then 2.

insert into public.ca_clubs (name) values
    ('A.C. Connecticut'),
    ('Ajax'),
    ('Ansonia Soccer Club'),
    ('Avon Soccer Club'),
    ('Beachside Soccer Club'),
    ('Berlin Youth Soccer Association'),
    ('Bethel Youth Soccer Association'),
    ('Bloomfield Junior Soccer Association'),
    ('Bolton Soccer'),
    ('Branford Soccer Club'),
    ('Bridgeport Hawks'),
    ('Bridgeport Scorpions FC'),
    ('Bristol Soccer Club'),
    ('Brookfield Soccer Club'),
    ('Burlington Junior Soccer Association'),
    ('Cantebury Soccer Club'),
    ('Canton Youth Soccer Association'),
    ('CFC Ole Football Club'),
    ('CFC South'),
    ('Chelsea Piers Shoreline SC'),
    ('Cheshire Soccer Club'),
    ('Clinton Invitational Tournament'),
    ('Clinton Youth Soccer Association'),
    ('Coginchaug Soccer Club'),
    ('Colchester Youth Soccer'),
    ('Columbia Windham Soccer Alliance'),
    ('Connecticut FC'),
    ('Connecticut Shamrocks'),
    ('Coventry Soccer'),
    ('Cromwell Chill Soccer Club'),
    ('CT Impact United Soccer Academy'),
    ('Darien Soccer Association'),
    ('Derby Youth Soccer'),
    ('DOCA Futbol Academy'),
    ('East Granby Soccer Association'),
    ('East Haddam Soccer Club'),
    ('East Hampton Soccer Club'),
    ('East Hartford Soccer Club'),
    ('East Haven Youth Soccer'),
    ('East Lyme Soccer Association'),
    ('Easton Redding United Soccer'),
    ('East Windsor Soccer Club'),
    ('EC Soccer'),
    ('Ellington Parks and Recreation'),
    ('Enfield Soccer Association'),
    ('Fairfield United Soccer Association'),
    ('Farmington Soccer Club'),
    ('FC North'),
    ('Foundation Sports Club'),
    ('FSA Farmington Sports Arena FC'),
    ('Ginga FC'),
    ('Glastonbury Hartwell Soccer Club'),
    ('Granby Rovers Soccer Club'),
    ('Green Warriors Soccer Academy'),
    ('Greenwich Soccer Association'),
    ('Griswold Soccer Club'),
    ('Groton Soccer Club'),
    ('GZS United'),
    ('Hamden Soccer Association'),
    ('Hartford Athletic'),
    ('Hartford Lions Soccer Academy'),
    ('Hartford Premier and Developmental'),
    ('Hartford Soccer Club (includes Hartford Hellions)'),
    ('JA Elite FC'),
    ('JCFC'),
    ('Lebanon Soccer Club'),
    ('Ledyard Soccer Club'),
    ('Litchfield Soccer Club'),
    ('Lyme-Old lyme Soccer Club'),
    ('Madison Invitational Tournament'),
    ('Madison Youth Soccer'),
    ('Manchester Soccer Club'),
    ('Meriden Soccer Club'),
    ('Middletown Youth Soccer'),
    ('Milford United Soccer Club'),
    ('Monroe Soccer Club'),
    ('Montville Youth Soccer Club'),
    ('Naugatuck Youth Soccer'),
    ('NECONN Soccer Club'),
    ('New Britain Youth Soccer'),
    ('New Canaan FC'),
    ('New Fairfield Soccer Club'),
    ('New Haven Youth Soccer'),
    ('New London Soccer Club'),
    ('Newtown Soccer Club'),
    ('North Branford Soccer Club'),
    ('Northeast United Soccer Club'),
    ('North Haven Soccer Club'),
    ('Northwest United Soccer Club'),
    ('Norwalk Community Soccer Club'),
    ('Norwalk Junior Soccer'),
    ('Norwich Police Athletic League'),
    ('Norwich Youth Soccer Club'),
    ('Oakwood Soccer Club'),
    ('Old Greenwich Riverside CC'),
    ('Old Saybrook Soccer Club'),
    ('Orange Soccer Association and Amity Soccer Club and Woodbridge'),
    ('Oxford Soccer League'),
    ('Plainfield Soccer Club'),
    ('Plainville Soccer Club'),
    ('Pomperaug (includes Middlebury & Southbury) Soccer Club'),
    ('Portland Soccer Club'),
    ('Prospect Dynamo Soccer Club'),
    ('PSC Dynamo CT'),
    ('Revolution United FC'),
    ('RHAM Youth Soccer'),
    ('Rocky Hill Soccer Club'),
    ('Rowayton Soccer Club'),
    ('Seymour Soccer Association'),
    ('Shelton Youth Soccer Organization'),
    ('Shepaug Soccer Club'),
    ('Simmons Soccer Club'),
    ('Simsbury Soccer Club'),
    ('Soccer Club of Guilford'),
    ('Soccer Club of Newington'),
    ('Soccer Club of New Milford'),
    ('Soccer Club of Ridgefield'),
    ('Somers Soccer Association'),
    ('Southeast Soccer Club'),
    ('Southington Soccer Club'),
    ('South Windsor Soccer Club'),
    ('Sporting FC'),
    ('Sterling Advanced Futbol Club'),
    ('Stonington SC'),
    ('Suffield Soccer Club'),
    ('Sylvie Poulin Columbus Day Classic'),
    ('Terryville Youth Soccer Club'),
    ('Thomaston Soccer Club'),
    ('Tolland Soccer Club'),
    ('Torrington Youth Soccer Club'),
    ('Tournment'),
    ('Trumbull United Soccer Club'),
    ('Vale Sports Club'),
    ('Valley FC'),
    ('Valley Regional Soccer Club'),
    ('Vernon Soccer Club'),
    ('Wallingford Youth Soccer'),
    ('WAM United Soccer Club'),
    ('Waterford Soccer Club'),
    ('Watertown Association Youth Soccer'),
    ('Westbrook Soccer Club'),
    ('West Hartford Soccer Club Girls'),
    ('West Hartford YSA Boys'),
    ('West Haven Youth Soccer'),
    ('Weston Soccer Club'),
    ('Westport Soccer Association'),
    ('Wethersfield Soccer Club'),
    ('Wilton Soccer Association'),
    ('Windsor Locks Soccer Club'),
    ('Windsor Soccer Club'),
    ('Winsted Youth Soccer Association'),
    ('Wolcott Youth Athletic Assc.'),
    ('Woodbridge Soccer Club'),
    ('Woodbury Bethlehem Youth Soccer')
on conflict do nothing;

-- CA's generic entries, flagged so nothing ever auto-resolves to them.
insert into public.ca_clubs (name, is_fallback) values
    ('Other', true),
    ('Referee Services Assignor', true)
on conflict do nothing;

-- Check:  select count(*) from public.ca_clubs;              -- 142
--         select name from public.ca_clubs where is_fallback;
